name: Deploy mdBook with plugins (latest)
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jontze/action-mdbook@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          # Optional Plugins have to be enabled
          #use-linkcheck: true
          use-mermaid: true
          #use-toc: true
          #use-opengh: true
      - name: Show mdbook version
        run: mdbook --version
      # - name: Show linkchecker version
      #   run: mdbook-linkcheck --version
      - name: Show mermaid version
        run: mdbook-mermaid --version
      # - name: Show toc version
      #   run: mdbook-toc --version
      # - name: Show open-on-gh version
      #   run: mdbook-open-on-gh --version
      - name: Build
        run: cd apunte && mdbook build
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apunte/book
